name: RSpec Tests

# Trigger the workflow on any push to any branch
on:
  push:
    branches:
      - "*"  # Trigger on all branches

# Define the jobs in the workflow
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.5  # Your project's Ruby version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bundle install

      # Step 4: Run RSpec tests
      - name: Run RSpec tests
        run: bundle exec rspec
